# Generated by Django 6.0.8 on 2026-09-08 23:03

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0241_nullify_empty_cable_end'),
        ('extras', '0140_imageattachment_image_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='UCKConsole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.CharField(max_length=200)),
                ('verify_tls', models.BooleanField(default=False)),
                ('integration_api_key_encrypted', models.CharField(blank=True, default='', max_length=500)),
                ('unifi_site_id', models.CharField(blank=True, default='', max_length=100)),
                ('design_username_encrypted', models.CharField(blank=True, default='', max_length=500)),
                ('design_password_encrypted', models.CharField(blank=True, default='', max_length=500)),
                ('comments', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unifi_consoles', to='dcim.site')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'UCK Console',
                'verbose_name_plural': 'UCK Consoles',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('module', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField(blank=True, null=True)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('detail', models.TextField(blank=True, default='')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='netbox_unifi_aio.uckconsole')),
            ],
            options={
                'verbose_name': 'UniFi Sync-Log',
                'verbose_name_plural': 'UniFi Sync-Logs',
                'ordering': ('-started',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UnifiDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('unifi_id', models.CharField(max_length=100)),
                ('mac_address', models.CharField(db_index=True, max_length=17)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('model', models.CharField(blank=True, default='', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=50)),
                ('adopted', models.BooleanField(default=False)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='netbox_unifi_aio.uckconsole')),
                ('netbox_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unifi_source', to='dcim.device')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'UniFi Device',
                'verbose_name_plural': 'UniFi Devices',
                'ordering': ('name', 'mac_address'),
                'unique_together': {('console', 'unifi_id')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='UnifiFloorplanMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('unifi_map_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='netbox_unifi_aio/design/')),
                ('width_px', models.PositiveIntegerField(blank=True, null=True)),
                ('height_px', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_walls', models.JSONField(blank=True, default=list)),
                ('raw_devices', models.JSONField(blank=True, default=list)),
                ('floorplan_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floorplan_maps', to='netbox_unifi_aio.uckconsole')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'UniFi Floorplan Map',
                'verbose_name_plural': 'UniFi Floorplan Maps',
                'ordering': ('name',),
                'unique_together': {('console', 'unifi_map_id')},
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
    ]
